package dao;

// Generated 2009-11-28 17:19:40 by Hibernate Tools 3.2.5.Beta

/**
 * Auto generated by hbm2java
 */
public class Auto implements java.io.Serializable {

	private int id;
	private int idClient;
	private Integer type;
	private String nr;

	public Auto() {
	}

	public Auto(int id, int idClient, String nr) {
		this.id = id;
		this.idClient = idClient;
		this.nr = nr;
	}

	public Auto(int id, int idClient, Integer type, String nr) {
		this.id = id;
		this.idClient = idClient;
		this.type = type;
		this.nr = nr;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getNr() {
		return this.nr;
	}

	public void setNr(String nr) {
		this.nr = nr;
	}

}
