package dao;

// Generated 2009-11-28 17:19:40 by Hibernate Tools 3.2.5.Beta

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int id;
	private String surname;
	private String name;
	private String pesel;

	public Client() {
	}

	public Client(int id, String surname, String name, String pesel) {
		this.id = id;
		this.surname = surname;
		this.name = name;
		this.pesel = pesel;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPesel() {
		return this.pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}

}
