package dao;

// Generated 2009-11-28 17:19:40 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * TimeId generated by hbm2java
 */
public class TimeId implements java.io.Serializable {

	private int id;
	private int idAuto;
	private Date timeFrom;
	private Date timeTo;

	public TimeId() {
	}

	public TimeId(int id, int idAuto, Date timeFrom) {
		this.id = id;
		this.idAuto = idAuto;
		this.timeFrom = timeFrom;
	}

	public TimeId(int id, int idAuto, Date timeFrom, Date timeTo) {
		this.id = id;
		this.idAuto = idAuto;
		this.timeFrom = timeFrom;
		this.timeTo = timeTo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdAuto() {
		return this.idAuto;
	}

	public void setIdAuto(int idAuto) {
		this.idAuto = idAuto;
	}

	public Date getTimeFrom() {
		return this.timeFrom;
	}

	public void setTimeFrom(Date timeFrom) {
		this.timeFrom = timeFrom;
	}

	public Date getTimeTo() {
		return this.timeTo;
	}

	public void setTimeTo(Date timeTo) {
		this.timeTo = timeTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimeId))
			return false;
		TimeId castOther = (TimeId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdAuto() == castOther.getIdAuto())
				&& ((this.getTimeFrom() == castOther.getTimeFrom()) || (this
						.getTimeFrom() != null
						&& castOther.getTimeFrom() != null && this
						.getTimeFrom().equals(castOther.getTimeFrom())))
				&& ((this.getTimeTo() == castOther.getTimeTo()) || (this
						.getTimeTo() != null
						&& castOther.getTimeTo() != null && this.getTimeTo()
						.equals(castOther.getTimeTo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdAuto();
		result = 37 * result
				+ (getTimeFrom() == null ? 0 : this.getTimeFrom().hashCode());
		result = 37 * result
				+ (getTimeTo() == null ? 0 : this.getTimeTo().hashCode());
		return result;
	}

}
