package dao;

// Generated 2009-11-28 17:19:40 by Hibernate Tools 3.2.5.Beta

/**
 * Time generated by hbm2java
 */
public class Time implements java.io.Serializable {

	private TimeId id;

	public Time() {
	}

	public Time(TimeId id) {
		this.id = id;
	}

	public TimeId getId() {
		return this.id;
	}

	public void setId(TimeId id) {
		this.id = id;
	}

}
