package dao;

// Generated 2009-11-28 17:19:40 by Hibernate Tools 3.2.5.Beta

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private String login;
	private String pass;
	private Integer role;

	public User() {
	}

	public User(int id, String login) {
		this.id = id;
		this.login = login;
	}

	public User(int id, String login, String pass, Integer role) {
		this.id = id;
		this.login = login;
		this.pass = pass;
		this.role = role;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

}
