package dao2;

// Generated 2009-11-28 22:17:34 by Hibernate Tools 3.2.5.Beta

/**
 * Auto generated by hbm2java
 */
public class Auto implements java.io.Serializable {
	static final int OSOB = 0;
	static final int CIEZ = 1;
	private int idAuto;
	private int idClient;
	private Integer type;
	private String nr;

	public Auto() {
	}

	public Auto(int idAuto, int idClient, String nr) {
		this.idAuto = idAuto;
		this.idClient = idClient;
		this.nr = nr;
	}

	public Auto(int idAuto, int idClient, Integer type, String nr) {
		this.idAuto = idAuto;
		this.idClient = idClient;
		this.type = type;
		this.nr = nr;
	}

	public int getIdAuto() {
		return this.idAuto;
	}

	public void setIdAuto(int idAuto) {
		this.idAuto = idAuto;
	}

	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getNr() {
		return this.nr;
	}

	public void setNr(String nr) {
		this.nr = nr;
	}

}
