package dao2;

// Generated 2009-11-28 22:17:34 by Hibernate Tools 3.2.5.Beta

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int idClient;
	private String surname;
	private String name;
	private String pesel;

	public Client() {
	}

	public Client(int idClient, String surname, String name, String pesel) {
		this.idClient = idClient;
		this.surname = surname;
		this.name = name;
		this.pesel = pesel;
	}

	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPesel() {
		return this.pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}

}
