package dao2;

// Generated 2009-11-28 22:17:34 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * Time generated by hbm2java
 */
public class Time implements java.io.Serializable {

	private int idTime;
	private int idAuto;
	private Date timeFrom;
	private Date timeTo;

	public Time() {
	}

	public Time(int idTime, int idAuto, Date timeFrom) {
		this.idTime = idTime;
		this.idAuto = idAuto;
		this.timeFrom = timeFrom;
	}

	public Time(int idTime, int idAuto, Date timeFrom, Date timeTo) {
		this.idTime = idTime;
		this.idAuto = idAuto;
		this.timeFrom = timeFrom;
		this.timeTo = timeTo;
	}

	public int getIdTime() {
		return this.idTime;
	}

	public void setIdTime(int idTime) {
		this.idTime = idTime;
	}

	public int getIdAuto() {
		return this.idAuto;
	}

	public void setIdAuto(int idAuto) {
		this.idAuto = idAuto;
	}

	public Date getTimeFrom() {
		return this.timeFrom;
	}

	public void setTimeFrom(Date timeFrom) {
		this.timeFrom = timeFrom;
	}

	public Date getTimeTo() {
		return this.timeTo;
	}

	public void setTimeTo(Date timeTo) {
		this.timeTo = timeTo;
	}

}
