package dao2;

// Generated 2009-11-28 22:17:34 by Hibernate Tools 3.2.5.Beta

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int idUser;
	private String login;
	private String pass;
	private Integer role;

	public User() {
	}

	public User(int idUser, String login) {
		this.idUser = idUser;
		this.login = login;
	}

	public User(int idUser, String login, String pass, Integer role) {
		this.idUser = idUser;
		this.login = login;
		this.pass = pass;
		this.role = role;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

}
